### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by joker5bb** [jeremy-jr-benthum/tor-button#1]
$ node -v
v7.9.0

$ node run.js

------------  Configure TOR  ------------
1. Start TOR connection
2. Log connection info
3. Stop TOR connection
4. Debug TOR connection
5. New TOR identity
6. Restart TOR connection
-----------------------------------------

----------------------------------------------
------------ Start Tor Connection ------------
----------------------------------------------

events.js:163
      throw er; // Unhandled 'error' event
      ^

Error: spawn tor ENOENT
    at exports._errnoException (util.js:1050:11)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:193:32)
    at onErrorNT (internal/child_process.js:367:16)
    at _combinedTickCallback (internal/process/next_tick.js:80:11)
    at process._tickCallback (internal/process/next_tick.js:104:9)

**Comment by Zander-Labuschagne** [comment]
I'm getting the same problem on Linux, when executing node run.js

**Comment by theFallen78** [comment]
any solution yet

**Comment by theFallen78** [comment]
solution mac: 
its not the node -v thats a problem
first run `brew install tor`
and install all the tor dependences 
edit run.sh 

`#!/usr/bin/env bash

# 'Wi-Fi' or 'Ethernet' or 'Display Ethernet'
INTERFACE=Wi-Fi

# Ask for the administrator password upfront
sudo -v

# Keep-alive: update existing `sudo` time stamp until finished
while true; do sudo -n true; sleep 60; kill -0 "$$" || exit; done 2>/dev/null &

# trap ctrl-c and call disable_proxy()
function disable_proxy() {
    sudo networksetup -setsocksfirewallproxystate $INTERFACE off
    echo "$(tput setaf 64)" #green
    echo "SOCKS proxy disabled."
    echo "$(tput sgr0)" # color reset
}
trap disable_proxy INT

# Let's roll
sudo networksetup -setsocksfirewallproxy $INTERFACE 127.0.0.1 9051 off
sudo networksetup -setsocksfirewallproxystate $INTERFACE on

echo "$(tput setaf 64)" # green
echo "SOCKS proxy 127.0.0.1:9051 enabled."
echo "$(tput setaf 136)" # orange
echo "Starting Tor..."
echo "$(tput sgr0)" # color reset

tor`

then 

rename `torrc.sample` to `torrc`

in /usr/local/etc/tor/

run `sh toh.sh`
