### ISSUE TITLE
Error unhandled event

### ISSUE THREAD

**Issue by BLCKPSTV** [jeremy-jr-benthum/tor-button#5]
Hi, 

I get this error when choosing option 1 in the run.sh

```
events.js:160
      throw er; // Unhandled 'error' event
      ^

Error: connect ECONNREFUSED 127.0.0.1:9051
    at Object.exports._errnoException (util.js:1022:11)
    at exports._exceptionWithHostPort (util.js:1045:20)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1087:14)
```

**Comment by pixelass** [comment]
+1

**Comment by pixelass** [comment]
I forgot to install Tor

```
brew install tor
```
